"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Check, ExternalLink, Globe2, Save, ShieldCheck, Smartphone, Apple, Monitor, X, Upload, Image as ImageIcon } from "lucide-react";

type OAuthClient = { id: string; clientId: string; name: string; redirectUris: string[]; scopes: string[]; isActive: boolean };
type Config = { applicationType: "WEB" | "SPA" | "ANDROID" | "IOS" | "DESKTOP"; authorizedOrigins: string[]; packageName: string | null; bundleId: string | null; certificateFingerprints: string[]; logoUrl: string | null; hasLogoUpload?: boolean; displayName: string | null; websiteUrl: string | null; manifestUrl: string | null; verificationStatus: string; verifiedAt: string | null };

const permissions = [["identity:read", "User ID", "Identify the signed-in MAX account."],["profile:read", "Basic profile", "Name, username and profile picture."],["email:read", "Email address", "Email and verification state."],["memory:read", "MAX Memory", "Read memory data approved by the user."],["offline_access", "Stay signed in", "Use refresh tokens for longer sessions."]] as const;
const types = { WEB: ["Web application", Globe2], SPA: ["Single-page app", Globe2], ANDROID: ["Android app", Smartphone], IOS: ["iPhone & iPad app", Apple], DESKTOP: ["Desktop app", Monitor] } as const;
const inputStyle: React.CSSProperties = { width: "100%", marginTop: 7, border: "1px solid var(--border)", borderRadius: 12, background: "var(--surface)", color: "var(--text)", padding: "12px 13px", outline: "none", fontSize: 12 };

export default function ConfigurationPage({ params }: { params: Promise<{ clientId: string }> }) {
  const [client, setClient] = useState<OAuthClient | null>(null); const [config, setConfig] = useState<Config | null>(null); const [scopes, setScopes] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [verifying, setVerifying] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(false); const [verified, setVerified] = useState(false); const [id, setId] = useState("");
  useEffect(() => { let mounted = true; void params.then(({ clientId }) => { setId(clientId); return Promise.all([fetch(`/api/applications/${encodeURIComponent(clientId)}`, { cache: "no-store" }), fetch(`/api/applications/${encodeURIComponent(clientId)}/config`, { cache: "no-store" })]).then(async ([a, c]) => { const ad = await a.json(); const cd = await c.json(); if (!a.ok) throw new Error(ad.message || "Unable to load application."); if (!c.ok) throw new Error(cd.message || "Unable to load client configuration."); if (!mounted) return; setClient(ad.client); setScopes(ad.client.scopes || []); setConfig(cd.config); }).catch((e) => mounted && setError(e instanceof Error ? e.message : "Unable to load configuration.")).finally(() => mounted && setLoading(false)); }); return () => { mounted = false; }; }, [params]);
  const update = (patch: Partial<Config>) => setConfig((current) => current ? { ...current, ...patch } : current);
  const arrayChange = (key: "authorizedOrigins" | "certificateFingerprints", index: number, value: string) => update({ [key]: config![key].map((item, i) => i === index ? value : item) } as Partial<Config>);
  async function uploadLogo(file: File) { if (!config) return; setUploading(true); setError(""); try { const form = new FormData(); form.append("file", file); const response = await fetch(`/api/applications/${encodeURIComponent(id)}/config`, { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to upload logo."); update({ logoUrl: data.logoUrl || null, hasLogoUpload: true }); } catch (e) { setError(e instanceof Error ? e.message : "Unable to upload logo."); } finally { setUploading(false); } }
  async function removeLogo() { setUploading(true); setError(""); try { const response = await fetch(`/api/applications/${encodeURIComponent(id)}/config`, { method: "DELETE" }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.message || "Unable to remove logo."); update({ logoUrl: null, hasLogoUpload: false }); } catch (e) { setError(e instanceof Error ? e.message : "Unable to remove logo."); } finally { setUploading(false); } }
  async function save() { if (!client || !config) return; setSaving(true); setError(""); setSaved(false); setVerified(false); try { const [scopeResponse, configResponse] = await Promise.all([fetch(`/api/applications/${encodeURIComponent(client.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scopes }) }), fetch(`/api/applications/${encodeURIComponent(client.id)}/config`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...config, authorizedOrigins: config.authorizedOrigins.map((v) => v.trim()).filter(Boolean), certificateFingerprints: config.certificateFingerprints.map((v) => v.trim()).filter(Boolean) }) })]); const sd = await scopeResponse.json(); const cd = await configResponse.json(); if (!scopeResponse.ok) throw new Error(sd.message || "Unable to save permissions."); if (!configResponse.ok) throw new Error(cd.message || "Unable to save configuration."); setConfig(cd.config); setScopes(sd.client?.scopes || scopes); setSaved(true); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save configuration."); } finally { setSaving(false); } }
  async function verifyManifest() { if (!client || !config?.manifestUrl) return; setVerifying(true); setError(""); setVerified(false); try { const response = await fetch(`/api/applications/${encodeURIComponent(client.id)}/verify-manifest`, { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to verify manifest."); if (!data.verified) { const failed = Object.entries(data.checks || {}).filter(([, ok]) => !ok).map(([key]) => key).join(", "); throw new Error(failed ? `Manifest verification failed: ${failed}.` : "Manifest verification failed."); } update({ verificationStatus: "VERIFIED", verifiedAt: new Date().toISOString() }); setVerified(true); } catch (e) { setError(e instanceof Error ? e.message : "Unable to verify manifest."); } finally { setVerifying(false); } }
  if (loading) return <main className="content"><section className="card" style={{ height: 260 }} /></main>;
  if (!client || !config) return <main className="content"><div className="auth-error">{error || "Application not found."}</div></main>;
  const [typeName, TypeIcon] = types[config.applicationType];
  return <div className="shell"><aside className="sidebar"><div className="brand"><div className="logo">M</div><div className="brand-copy"><div className="brand-name">MAX</div><div className="brand-sub">Developer Platform</div></div></div><nav className="nav"><div className="nav-group"><div className="nav-label">Platform</div><Link href="/" className="nav-item"><span>Home</span></Link><Link href="/applications" className="nav-item active"><span>Applications</span></Link></div></nav><div className="sidebar-foot"><strong>MAX AI Ecosystem</strong><br/>Build experiences that connect to MAX.</div></aside><div className="main"><header className="topbar"><div className="breadcrumb">Applications / Full configuration</div></header><main className="content"><div style={{ marginBottom: 20 }}><Link href={`/applications/${encodeURIComponent(id)}`} style={{ display: "inline-flex", alignItems: "center", gap: 7, color: "var(--muted)", fontSize: 12, fontWeight: 700 }}><ArrowLeft size={15}/>Application</Link></div>{error ? <div className="auth-error">{error}</div> : null}<div className="hero"><div><div className="eyebrow">MAX Developers</div><h1>{config.displayName || client.name}</h1><p className="lead">Full OAuth configuration synced directly with MAX Auth.</p></div><div style={{ display: "flex", alignItems: "center", gap: 8 }}><TypeIcon size={18}/><span className="status">{typeName}</span></div></div>
<section className="card" style={{ marginTop: 20 }}><div className="section-heading"><div><h2>Permissions</h2><p>These are the permissions this client is allowed to request.</p></div></div><div className="scope-grid" style={{ marginTop: 16 }}>{permissions.map(([scopeId, title, description]) => { const active = scopes.includes(scopeId); return <button key={scopeId} type="button" onClick={() => setScopes((current) => active ? current.filter((item) => item !== scopeId) : [...current, scopeId])} className="scope-option" style={{ textAlign: "left", border: active ? "1px solid var(--brand)" : undefined }}><span><strong>{title}</strong><small>{description}</small><code style={{ display: "block", marginTop: 5, fontSize: 10 }}>{scopeId}</code></span>{active ? <Check size={16}/> : null}</button>; })}</div></section>
<section className="card" style={{ marginTop: 16 }}><div className="section-heading"><div><h2>Branding & client identity</h2><p>Displayed on MAX authorization and consent screens.</p></div></div><div style={{ display: "grid", gap: 16, marginTop: 16 }}><label className="field-label">Application name<input value={config.displayName || ""} onChange={(e) => update({ displayName: e.target.value || null })} style={inputStyle}/></label><div className="field-label"><span>Application logo</span><div style={{ display: "flex", gap: 14, alignItems: "center", marginTop: 8, flexWrap: "wrap" }}>{config.logoUrl ? <div style={{ width: 72, height: 72, border: "1px solid var(--border)", borderRadius: 16, overflow: "hidden", background: "var(--surface)", display: "grid", placeItems: "center" }}><img src={config.logoUrl} alt="Application logo" style={{ width: "100%", height: "100%", objectFit: "contain" }}/></div> : <div style={{ width: 72, height: 72, border: "1px dashed var(--border)", borderRadius: 16, display: "grid", placeItems: "center", color: "var(--muted)" }}><ImageIcon size={22}/></div>}<div style={{ display: "flex", gap: 8, alignItems: "center" }}><label className="secondary" style={{ display: "inline-flex", alignItems: "center", gap: 7, cursor: uploading ? "wait" : "pointer" }}><Upload size={14}/>{uploading ? "Uploading…" : "Upload image"}<input type="file" accept="image/png,image/jpeg,image/webp" hidden disabled={uploading} onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadLogo(file); e.currentTarget.value = ""; }}/></label>{config.logoUrl ? <button className="secondary" type="button" onClick={() => void removeLogo()} disabled={uploading}>Remove</button> : null}</div></div><small style={{ display: "block", marginTop: 7, color: "var(--muted)" }}>PNG, JPEG or WebP · 512 KB maximum</small></div><label className="field-label">Logo URL<input value={config.logoUrl || ""} onChange={(e) => update({ logoUrl: e.target.value || null, hasLogoUpload: false })} placeholder="https://example.com/logo.png" style={inputStyle}/></label><label className="field-label">Website URL<input value={config.websiteUrl || ""} onChange={(e) => update({ websiteUrl: e.target.value || null })} placeholder="https://example.com" style={inputStyle}/></label></div></section>
<section className="card" style={{ marginTop: 16 }}><div className="section-heading"><div><h2>Redirects & authorized sites</h2><p>MAX Auth will only use registered redirect destinations.</p></div></div><div style={{ display: "grid", gap: 16, marginTop: 16 }}><div className="field-label">Redirect URIs<div style={{ display: "grid", gap: 8, marginTop: 7 }}>{client.redirectUris.map((uri) => <div key={uri} className="credential"><code style={{ overflowWrap: "anywhere" }}>{uri}</code></div>)}</div><Link href={`/applications/${encodeURIComponent(id)}`} className="secondary" style={{ display: "inline-flex", marginTop: 8 }}>Edit redirect URIs</Link></div><div className="field-label">Authorized origins<div style={{ display: "grid", gap: 8, marginTop: 7 }}>{config.authorizedOrigins.map((origin, i) => <div key={i} style={{ display: "flex", gap: 8 }}><input value={origin} onChange={(e) => arrayChange("authorizedOrigins", i, e.target.value)} style={inputStyle}/>{config.authorizedOrigins.length > 1 ? <button className="icon-button" onClick={() => update({ authorizedOrigins: config.authorizedOrigins.filter((_, j) => j !== i) })}><X size={15}/></button> : null}</div>)}<button className="secondary" onClick={() => update({ authorizedOrigins: [...config.authorizedOrigins, ""] })}>+ Add authorized site</button></div></div></div></section>
<section className="card" style={{ marginTop: 16 }}><div className="section-heading"><div><h2>Platform identity & verification</h2><p>Use these values to bind applications to their registered identity.</p></div></div><div style={{ marginTop: 16, display: "grid", gap: 14 }}><label className="field-label">MAX client manifest URL<input value={config.manifestUrl || ""} onChange={(e) => { update({ manifestUrl: e.target.value || null, verificationStatus: e.target.value ? "PENDING" : "UNVERIFIED", verifiedAt: null }); setVerified(false); }} placeholder="https://example.com/.well-known/max-auth.json" style={inputStyle}/><small style={{ color: "var(--muted)" }}>The manifest must declare this exact client ID, website, every registered redirect URI, and S256 PKCE.</small></label><div className="notice"><ShieldCheck size={18}/><div style={{ flex: 1 }}><strong>Manifest verification: {config.verificationStatus}</strong><p>{config.verifiedAt ? `Verified ${new Date(config.verifiedAt).toLocaleString()}` : config.manifestUrl ? "Ready to verify the registered manifest." : "No manifest URL registered."}</p></div>{config.manifestUrl ? <button className="secondary" type="button" onClick={() => void verifyManifest()} disabled={verifying}>{verifying ? "Verifying…" : verified || config.verificationStatus === "VERIFIED" ? "Verify again" : "Verify manifest"}</button> : null}</div>{config.applicationType === "ANDROID" && <label className="field-label">Android package name<input value={config.packageName || ""} onChange={(e) => update({ packageName: e.target.value || null })} style={inputStyle}/></label>}{config.applicationType === "IOS" && <label className="field-label">iOS Bundle ID<input value={config.bundleId || ""} onChange={(e) => update({ bundleId: e.target.value || null })} style={inputStyle}/></label>}{(config.applicationType === "ANDROID" || config.applicationType === "IOS") && <div className="field-label">Certificate / signing fingerprints<div style={{ display: "grid", gap: 8, marginTop: 7 }}>{config.certificateFingerprints.map((fp, i) => <div key={i} style={{ display: "flex", gap: 8 }}><input value={fp} onChange={(e) => arrayChange("certificateFingerprints", i, e.target.value)} style={inputStyle}/>{config.certificateFingerprints.length > 1 ? <button className="icon-button" onClick={() => update({ certificateFingerprints: config.certificateFingerprints.filter((_, j) => j !== i) })}><X size={15}/></button> : null}</div>)}<button className="secondary" onClick={() => update({ certificateFingerprints: [...config.certificateFingerprints, ""] })}>+ Add fingerprint</button></div></div>}</div></section>
<div style={{ display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 18 }}>{saved ? <span className="status" style={{ display: "inline-flex", alignItems: "center", gap: 6 }}><Check size={14}/>Saved</span> : null}<button className="primary" onClick={() => void save()} disabled={saving}>{saving ? "Saving…" : <><Save size={15}/>Save full configuration</>}</button></div><div className="footer"><Link href="/applications">← Applications</Link><Link href="https://auth.max-ai.name.ng/developer" target="_blank">MAX Auth <ExternalLink size={12}/></Link></div></main></div></div>;
}
