"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Activity, ArrowLeft, CheckCircle2, Clock3, KeyRound, LockKeyhole, ShieldCheck, XCircle } from "lucide-react";

type AuditLog = { id: string; action: string; ipAddress?: string | null; createdAt: string };
type Consent = { id: string; scopes: string[]; grantedAt: string; client?: { name: string; clientId: string } };
const labels: Record<string, string> = { LOGIN_SUCCESS: "Signed in", LOGIN_FAILED: "Failed sign-in", LOGOUT: "Signed out", TOKEN_REFRESH: "Session refreshed", PASSWORD_CHANGED: "Password changed", EMAIL_VERIFIED: "Email verified", DEVICE_TRUSTED: "Device trusted", DEVICE_REVOKED: "Device revoked", SESSION_REVOKED: "Session revoked", TWO_FA_ENABLED: "Two-factor authentication enabled", TWO_FA_DISABLED: "Two-factor authentication disabled", OAUTH_CLIENT_CREATED: "OAuth application created", OAUTH_CLIENT_SECRET_ROTATED: "OAuth secret rotated", OAUTH_CONSENT_GRANTED: "OAuth access approved", OAUTH_CONSENT_REVOKED: "OAuth access revoked", PROFILE_UPDATED: "Profile updated", REGISTER: "Account created" };
function formatAction(action: string) { return labels[action] ?? action.replaceAll("_", " ").toLowerCase().replace(/^./, (c) => c.toUpperCase()); }
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }

export default function SecurityPage() {
  const [logs, setLogs] = useState<AuditLog[]>([]); const [consents, setConsents] = useState<Consent[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [revoking, setRevoking] = useState("");
  async function load() { setLoading(true); setError(""); try { const [a, c] = await Promise.all([fetch("/api/security/audit-logs", { cache: "no-store" }), fetch("/api/security/consents", { cache: "no-store" })]); const ab = await a.json().catch(() => null); const cb = await c.json().catch(() => null); if (!a.ok) throw new Error(ab?.message || "Unable to load security events."); if (!c.ok) throw new Error(cb?.message || "Unable to load OAuth access."); setLogs(Array.isArray(ab?.data?.logs) ? ab.data.logs : []); setConsents(Array.isArray(cb?.data?.consents) ? cb.data.consents : []); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load security data."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function revokeConsent(id: string) { if (!window.confirm("Revoke this application's access? Its active OAuth tokens will also be revoked.")) return; setRevoking(id); try { const response = await fetch(`/api/security/consents/${encodeURIComponent(id)}`, { method: "DELETE" }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.message || "Unable to revoke access."); setConsents((items) => items.filter((item) => item.id !== id)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to revoke access."); } finally { setRevoking(""); } }
  return <div className="shell"><aside className="sidebar"><div className="brand"><div className="logo">M</div><div className="brand-copy"><div className="brand-name">MAX</div><div className="brand-sub">Developer Platform</div></div></div><nav className="nav"><div className="nav-group"><div className="nav-label">Manage</div><Link href="/security" className="nav-item active"><ShieldCheck/><span>Security</span></Link><Link href="/credentials" className="nav-item"><KeyRound/><span>Credentials</span></Link><Link href="/activity" className="nav-item"><Activity/><span>Activity</span></Link></div></nav></aside><div className="main"><header className="topbar"><div className="breadcrumb">Security</div><div className="avatar">M</div></header><main className="content"><div className="eyebrow">Developer security</div><h1>Security</h1><p className="lead">Manage OAuth access and review security events connected to your MAX account.</p>
  <div className="grid" style={{ marginTop: 28 }}><div className="card"><ShieldCheck color="var(--blue)" size={20}/><div className="eyebrow" style={{ marginTop: 14 }}>OAuth access</div><div className="metric">{loading ? "—" : consents.length}</div><div className="metric-note">Active applications with approved access</div></div><div className="card"><Activity color="var(--blue)" size={20}/><div className="eyebrow" style={{ marginTop: 14 }}>Security events</div><div className="metric">{loading ? "—" : logs.length}</div><div className="metric-note">Events currently available from MAX Auth</div></div><div className="card"><LockKeyhole color="var(--blue)" size={20}/><div className="eyebrow" style={{ marginTop: 14 }}>Token protection</div><div className="metric" style={{ fontSize: 22 }}>Protected</div><div className="metric-note">Secrets and tokens are never displayed here</div></div></div>
  {error && <div className="notice" style={{ marginTop: 18 }}><XCircle size={18}/><div><strong>Security data could not be fully loaded</strong><p>{error}</p></div></div>}
  <section className="section"><div className="section-head"><div><h2 className="section-title">Authorized applications</h2><p className="section-desc">OAuth applications that currently have access to your MAX account.</p></div><ShieldCheck size={20}/></div><div className="card list">{!loading && consents.length === 0 && <div className="empty-state"><ShieldCheck size={22}/><strong>No active OAuth access</strong><span>Applications will appear here after you approve access.</span></div>}{consents.map((consent) => <div className="list-row" key={consent.id}><div className="icon-box"><KeyRound size={18}/></div><div className="row-main"><div className="row-title">{consent.client?.name || "MAX application"}</div><div className="row-sub">{consent.client?.clientId || "Client ID unavailable"} · Approved {formatDate(consent.grantedAt)} · {consent.scopes.join(", ")}</div></div><button className="button secondary" disabled={revoking === consent.id} onClick={() => revokeConsent(consent.id)}>{revoking === consent.id ? "Revoking…" : "Revoke"}</button></div>)}</div></section>
  <section className="section"><div className="section-head"><div><h2 className="section-title">Recent security events</h2><p className="section-desc">Authentication, OAuth and account-security events from MAX Auth.</p></div><Clock3 size={20}/></div><div className="card list">{loading && <div className="empty-state"><Activity size={22}/><strong>Loading security events…</strong><span>Fetching the latest events from MAX Auth.</span></div>}{!loading && logs.length === 0 && <div className="empty-state"><Activity size={22}/><strong>No security events yet</strong><span>Important account and authorization events will appear here.</span></div>}{!loading && logs.map((log) => <div className="list-row" key={log.id}><div className="icon-box"><CheckCircle2 size={18}/></div><div className="row-main"><div className="row-title">{formatAction(log.action)}</div><div className="row-sub">{formatDate(log.createdAt)} · {log.ipAddress || "IP unavailable"}</div></div></div>)}</div></section>
  <div className="notice" style={{ marginTop: 18 }}><ShieldCheck size={18}/><div><strong>Security boundary</strong><p>MAX Developers does not store your MAX password. OAuth authorization, consent records, account security and token revocation remain controlled by MAX Auth.</p></div></div><div className="footer"><Link href="/"><ArrowLeft size={16}/> Back to dashboard</Link></div></main></div></div>;
}
